services:
  ats-app:
    build: .
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SENTENCE_TRANSFORMERS_HOME=/app/models  # Tell the library where to look
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./models:/app/models  # Link your local models folder to the container